name: Ultraverse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35486
title: Welcome to the Ultraverse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffc600'
    - '#002776'
    - '#e00034'
    - '#f38616'
    - '#e6382a'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
