name: Ultraverse
favicon: null
layout_spectrum: 0.9557975900825113
typography_spectrum: 0.11223534285090864
title: Welcome to the Ultraverse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00c6f3'
    - '#3b3456'
    - '#004adc'
    - '#776066'
    - '#4c51a2'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.25727738719433546
  rhythmicContrast: 0.5
purpose: []
